
import java.util.Random;
import javax.swing.*;

public class NewJFrame extends javax.swing.JFrame {

    String userInputString, user_attempts, name;
    int userGuessedNumber, attempt, i;

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtattempt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        how_to_play = new javax.swing.JButton();
        beginner = new javax.swing.JCheckBox();
        intermediate = new javax.swing.JCheckBox();
        expert = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Welcome to the number guessing game..");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("How many attempts do you want to guess the number?");

        txtattempt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("Enter your name.");

        user_name.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N

        how_to_play.setBackground(new java.awt.Color(153, 153, 255));
        how_to_play.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        how_to_play.setText("How to play ?");
        how_to_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how_to_playActionPerformed(evt);
            }
        });

        beginner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        beginner.setText("BEGINNER");
        beginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerActionPerformed(evt);
            }
        });

        intermediate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intermediate.setText("INTERMEDIATE");
        intermediate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermediateActionPerformed(evt);
            }
        });

        expert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expert.setText("EXPERT");
        expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("DIFFICULTY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtattempt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(how_to_play))))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(beginner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(intermediate, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                            .addComponent(expert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(how_to_play, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_name, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtattempt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(beginner, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(intermediate)
                .addGap(18, 18, 18)
                .addComponent(expert)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void how_to_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how_to_playActionPerformed
        JOptionPane.showMessageDialog(null, "1. Computer will generate a random number according to your difficulty level."
                + " \n 2. You have to guess that number. "
                + "\n 3. Select the number of attempts you want to guess the correct computer genereted number. \n");
    }//GEN-LAST:event_how_to_playActionPerformed

    private void beginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerActionPerformed
        Random random = new Random();
        int randomNumber = random.nextInt(101);
        attempt = Integer.valueOf(txtattempt.getText());
        name = String.valueOf(user_name.getText());
        JOptionPane.showMessageDialog(null, "Hii " + name + ", Let's play the Game.\n"
                + "You have to guess between 0 and 100.");

        for (i = 0; i < attempt; i++) {
            userInputString = JOptionPane.showInputDialog("Guess the number:");
            userGuessedNumber = Integer.parseInt(userInputString);
            if (userGuessedNumber > randomNumber) {
                JOptionPane.showMessageDialog(null, "Too high, try again");
            } else if (userGuessedNumber < randomNumber) {
                JOptionPane.showMessageDialog(null, "Too low,try again");
            } else {
                JOptionPane.showMessageDialog(null, "yes, you guessed the number on " + i + " attempt.");
                System.exit(0);
            }
        }
        JOptionPane.showMessageDialog(null, "Oops you lost the game..");
    }//GEN-LAST:event_beginnerActionPerformed

    private void intermediateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermediateActionPerformed
        Random random = new Random();
        int randomNumber = random.nextInt(201);
        attempt = Integer.valueOf(txtattempt.getText());
        name = String.valueOf(user_name.getText());
        JOptionPane.showMessageDialog(null, "Hii " + name + ", Let's play the Game.\n"
                + "You have to guess between 0 and 200.");

        for (i = 0; i < attempt; i++) {
            userInputString = JOptionPane.showInputDialog("Guess the number:");
            userGuessedNumber = Integer.parseInt(userInputString);
            if (userGuessedNumber > randomNumber) {
                JOptionPane.showMessageDialog(null, "Too high, try again");
            } else if (userGuessedNumber < randomNumber) {
                JOptionPane.showMessageDialog(null, "Too low,try again");
            } else {
                JOptionPane.showMessageDialog(null, "yes, you guessed the number on " + i + " attempt.");
                System.exit(0);
            }
        }
        JOptionPane.showMessageDialog(null, "Oops you lost the game..");
    }//GEN-LAST:event_intermediateActionPerformed

    private void expertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertActionPerformed
        Random random = new Random();
        int randomNumber = random.nextInt(301);
        attempt = Integer.valueOf(txtattempt.getText());
        name = String.valueOf(user_name.getText());
        JOptionPane.showMessageDialog(null, "Hii " + name + ", Let's play the Game.\n"
                + "You have to guess between 0 and 300.");

        for (i = 0; i < attempt; i++) {
            userInputString = JOptionPane.showInputDialog("Guess the number:");
            userGuessedNumber = Integer.parseInt(userInputString);
            if (userGuessedNumber > randomNumber) {
                JOptionPane.showMessageDialog(null, "Too high, try again");
            } else if (userGuessedNumber < randomNumber) {
                JOptionPane.showMessageDialog(null, "Too low,try again");
            } else {
                JOptionPane.showMessageDialog(null, "yes, you guessed the number on " + i + " attempt.");
                System.exit(0);
            }
        }
        JOptionPane.showMessageDialog(null, "Oops you lost the game..");
    }//GEN-LAST:event_expertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox beginner;
    private javax.swing.JCheckBox expert;
    private javax.swing.JButton how_to_play;
    private javax.swing.JCheckBox intermediate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtattempt;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
